### ISSUE TITLE
when using organization folders, prefix is not shown

### ISSUE THREAD

**Issue by alepouna** [alepouna/fastify-router#3]
If we have a folder structure as follows: 
![image](https://user-images.githubusercontent.com/98479040/209027547-57fe0574-acf2-47cd-af19-ac5a66ef595d.png)

Anything inside the **api** folder will have a root path `/` instead of `/api`

To fix this, we need an option to define prefixes

**Comment by auroraisluna** [comment]
Added in v1.0.3
